# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Notes Api
  description: Node project API
  version: "1.0.0"
# the domain of the service
host: localhost:3000
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /notes
produces:
  - application/json
paths:
  /:
    get:
      description: |
        Get all notes created
      responses:
        200:
          description: An array of notes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
        204:
          description: No notes found
    post:
      description: |
        Add a note
      responses:
        201:
          description: The note's id
          schema:
            type: object
            properties:
              id:
                type: string
  /{id}:
    get:
      description: |
        Get a note
      responses:
        200:
          description: A note
          schema:
            $ref: '#/definitions/Note'
        404:
          description: Note not found
    delete:
      description: |
        Delete a note
      responses:
        204:
          description: Note deleted
        404:
          description: Note not found
    parameters:
    - name: id
      in: path
      description: ID of note to use
      required: true
      type: string

definitions:
  Note:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      content:
        type: string
      date:
        type: number
